(source melpa)
(source gnu)

(depends-on "cask")
(depends-on "coffee-mode")
(depends-on "dash")
(depends-on "epl")
(depends-on "f")
(depends-on "git-commit-mode")
(depends-on "git-rebase-mode")
(depends-on "haml-mode")
(depends-on "magit")
(depends-on "markdown-mode")
(depends-on "pallet")
(depends-on "s")
(depends-on "sass-mode")
(depends-on "slim-mode")
(depends-on "yaml-mode")